name: Check my code syntax
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
